import express from 'express';
import { createUser, getAllUsers, getUserByID, deleteUserByID, updateUserDataByID} from '../controllers/users.controllers.js';
const router = express.Router();

  // POST 1 DATA posting data to the database of mongodb
  router.post('/', createUser)

  // GET ALL users from mongoDB database
  router.get('/', getAllUsers);

  // GET ONE user data with the help of ID generated by mongoDB itself
  router.get('/:id', getUserByID);

  // DELETE user by id
  router.delete('/:id', deleteUserByID);

    // PUT update data of the user by id
  router.put('/:id', updateUserDataByID);

export default router;